name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: codeception_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name toto
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: codeception_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, php-xml, ext-dom, pdo, pgsql, mysql, sqlite
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: php ./vendor/bin/codecept run
      env:
        DB_MYSQL_PASSWORD: root
        PGPASSWORD: postgres
        DB_MYSQL_PORT: 3306
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
        MYSQL_DATABASE: codeception_test
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        POSTGRESQL_HOST: 127.0.0.1
        POSTGRESQL_PORT: ${{ job.services.mysql.ports['3306'] }}
        POSTGRESQL_DATABASE: codeception_test
        POSTGRESQL_USER: root
        POSTGRESQL_PASSWORD: root
