name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: codeception_test
          MYSQL_PASSWORD: root
        ports: 
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: codeception_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, php-xml, ext-dom, pdo
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Start MySQL Server
      run: |
        #sudo mysqld_safe --skip-grant-tables --skip-networking &
        #sudo service mysql start
        #sudo systemctl start mysql
        #mysql -uroot -proot -e "create database codeception_test;"
        sudo service mysql status

    - name: Run test suite
      run: |
        php ./vendor/bin/codecept run
      env:
        DB_MYSQL_PASSWORD: root
        PGPASSWORD: postgres
